namespace MojiGotchi;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;
using Silk.NET.OpenAL;

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DISCLAIMER: The SoundManager class in almost entirely generated by AI (Google Gemini) with some minor modifications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
public static class SoundManager
{
    private static AL? _al;
    private static ALContext? _alc;
    private static unsafe Device* _device;
    private static unsafe Context* _context;

    private static float _volume = 0.9f;
    public static float Volume
    {
        get => _volume;
        set 
        {
            _volume = Math.Clamp(value, 0f, 1f);
            UpdateGlobalVolume();
        }
    }

    static SoundManager()
    {
        try
        {
            _al = AL.GetApi();
            _alc = ALContext.GetApi();

            unsafe
            {
                _device = _alc.OpenDevice("");
                if (_device == null) throw new Exception("Could not open audio device.");

                _context = _alc.CreateContext(_device, null);
                _alc.MakeContextCurrent(_context);
            }

            UpdateGlobalVolume();
        }
        catch (Exception ex)
        {
            DebugLogger.Log($"Audio Init Error: {ex.Message}");
        }
    }

    private static void UpdateGlobalVolume()
    {
        if (_al != null)
		{
			_al.SetListenerProperty(ListenerFloat.Gain, _volume);
		}
        
    }

    public static void PlaySound(byte[]? soundbytes)
    {
        if (soundbytes == null || soundbytes.Length < 44 || _al == null) return;

        try
        {
            using var ms = new MemoryStream(soundbytes);
            using var reader = new BinaryReader(ms);

            reader.ReadBytes(22);
            short channels = reader.ReadInt16();
            int sampleRate = reader.ReadInt32();
            reader.ReadBytes(6);
            short bitsPerSample = reader.ReadInt16();
            
            while (reader.BaseStream.Position < reader.BaseStream.Length)
            {
                string chunkId = new string(reader.ReadChars(4));
                int chunkSize = reader.ReadInt32();
                if (chunkId == "data")
                {
                    byte[] rawData = reader.ReadBytes(chunkSize);
                    BufferFormat format = GetBufferFormat(channels, bitsPerSample);

                    uint buffer = _al.GenBuffer();
                    
                    // Fix: Explicitly provide type argument and use correct overload
                    _al.BufferData<byte>(buffer, format, rawData, sampleRate);

                    uint source = _al.GenSource();
                    // Fix: Use SourceInteger.Buffer instead of SourceInt
                    _al.SetSourceProperty(source, SourceInteger.Buffer, (int)buffer);
                    _al.SourcePlay(source);

                    CleanupSourceAsync(source, buffer);
                    return;
                }
                else
                {
                    reader.BaseStream.Position += chunkSize;
                }
            }
        }
        catch (Exception ex)
        {
            DebugLogger.Log($"Playback Error: {ex.Message}");
        }
    }

    private static async void CleanupSourceAsync(uint source, uint buffer)
    {
		if(_al != null)
		{
			int state;
			do
			{
				await Task.Delay(100);
				_al.GetSourceProperty(source, GetSourceInteger.SourceState, out state);
			} while (state == (int)SourceState.Playing);

			_al.DeleteSource(source);
			_al.DeleteBuffer(buffer);
		}
        
    }

    private static BufferFormat GetBufferFormat(int channels, int bits)
    {
        return channels switch
        {
            1 => bits == 8 ? BufferFormat.Mono8 : BufferFormat.Mono16,
            2 => bits == 8 ? BufferFormat.Stereo8 : BufferFormat.Stereo16,
            _ => throw new NotSupportedException("Unsupported channel count")
        };
    }
}

public class Sounds
{
    private Dictionary<string, byte[]?> _library = new();

    public void AddSound(string name, string filename)
    {
        try
        {
            byte[] data = File.ReadAllBytes(filename);
            _library.Add(name, data);
			DebugLogger.Log($"Loaded sound: {filename}");
        }
        catch(Exception e)
        {
            DebugLogger.Log($"Error loading {filename}: {e.Message}");
        }
    }

    public byte[]? GetSound(string key) => _library.GetValueOrDefault(key);
}