@startuml
class LevelElementBlueprint {
    + Name : string <<get>>
    + IsBlocking : bool <<get>>
    + LevelElementBlueprint(name:string, animation:Animation, isBlocking:bool)
}
class BlueprintManager <<static>> {
    + {static} NumItems : int <<get>>
    + {static} Initialize() : void
    + {static} MakeBlueprint1(name:string, key:string, chars:char[], fg:Color, bg:Color, blocking:bool, animtime:int) : void
    + {static} MakeBlueprint1(name:string, key:string, character:char, fg:Color, bg:Color, blocking:bool, animtime:int) : void
    + {static} GetBlueprint(key:string) : LevelElementBlueprint?
    + {static} GetElement(key:string, pos:Vec2) : LevelElement?
    + {static} GetBlueprintElements(start:int, count:int) : Dictionary<string, LevelElement>
}
LevelElementBlueprint --> "Animation" Animation
@enduml
