@startuml
abstract class Entity {
    + Name : string <<get>> <<set>>
    + <<const>> AnimDefault : string = "DEFAULT"
    + Entity()
    + GetSprite() : Sprite?
    + Move(amount:Vec2) : void
    + Move(direction:int) : void
    + SetAnimation(state:string) : void
}
Entity --> "Animations<string,Animation>" "Dictionary`2"
Entity --> "Pos" Vec2
@enduml
