@startuml
class LM <<static>> {
    + {static} SetLanguage(language:string) : void
    + {static} Get(key:string) : string
    + {static} Get(key:string, args:object?[]) : string
    + {static} CurrentLang() : string
}
class MissingLang {
    + MissingLang()
    + UpdatePage(size:Vec2) : void
}
Modal <|-- MissingLang
@enduml
