@startuml
class OptionsJsonContext <<partial>> {
}
class OptionsJsonContextHelper <<static>> {
    + {static} Serialize(options:Dictionary<string, string>) : string
    + {static} Deserialize(json:string) : Dictionary<string, string>
}
class "Dictionary`2"<T1,T2> {
}
JsonSerializerContext <|-- OptionsJsonContext
@enduml
