@startuml
enum LoopResult {
    CONTINUE,
    QUIT,
    GOTOGAME,
    GOTOEDITOR,
}
class Program <<static>> {
}
class "Dictionary`2"<T1,T2> {
}
enum AppState {
    GAME,
    EDITOR,
    QUIT,
}
Program --> "GameOptions<string,string>" "Dictionary`2"
Program +-- AppState
@enduml
