@startuml
class Renderer {
    + Renderer(programBgColor:Color)
    + ConsoleWidth : int <<get>>
    + ConsoleHeight : int <<get>>
    + Resize(newWidth:int, newHeight:int, force:bool) : bool
    + ClearBuffer() : void
    + RenderScreen() : void
    + DrawSprite(sprite:Sprite?, position:Vec2, crop:SimpleRect?) : void
    + DrawText(text:string, position:Vec2, fgColor:Color, bgColor:Color) : void
    + DrawText(text:string, position:Vec2, fgColor:Color) : void
    + Shade(color:Color, amount:float, area:SimpleRect) : void
}
@enduml
