@startuml
class Stat {
    + Value : int <<get>> <<set>>
    + Min : int <<get>> <<set>>
    + Max : int <<get>> <<set>>
    + Default : int <<get>> <<set>>
    + UpdateInterval : int <<get>> <<set>>
    + Stat()
    + Stat(type:StatType, updateinterval:int, defaultValue:int, maxValue:int, minValue:int)
    + Raise(amount:int) : void
    + Lower(amount:int) : void
    + Reset() : void
}
Stat --> "Type" StatType
Stat --> "LastUpdated" DateTime
@enduml
